liveagent:
  communication:
    image:
      repository: acrapplications.azurecr.io/common/eventflowwebapi
      pullPolicy: Always
      tag: "master.4f199a0.7293914525"

  manager:
    image:
      repository: acrapplications.azurecr.io/common/eventflowwebapi
      pullPolicy: Always
      tag: "master.4f199a0.7293914525"

  timeout:
    image:
      repository: acrapplications.azurecr.io/common/eventflowwebapi
      pullPolicy: Always
      tag: "master.4f199a0.7293914525"


  keepalive:
    image:
      repository: acrapplications.azurecr.io/common/eventflowwebapi
      pullPolicy: Always
      tag: "master.4f199a0.7293914525"
