liveagent:
  communication:
    image:
      repository: acrapplications.azurecr.io/common/eventflowwebapi
      pullPolicy: Always
      tag: "release-SOE-10.e96945f.5812799663"

  manager:
    image:
      repository: acrapplications.azurecr.io/common/eventflowwebapi
      pullPolicy: Always
      tag: "release-SOE-10.d683844.5812802100"

  timeout:
    image:
      repository: acrapplications.azurecr.io/common/eventflowwebapi
      pullPolicy: Always
      tag: "release-v1.0.0-genesys-stefanini.dd1da67"


  keepalive:
    image:
      repository: acrapplications.azurecr.io/common/eventflowwebapi
      pullPolicy: Always
      tag: "release-v1.0.0-genesys-stefanini.e1678f5"
